import { For, Show, createResource, createSignal, onMount } from 'solid-js';
import { api, supabase, uploadIcs } from './api/client';
import './style.css';

type Event = { id:string; title:string; start_at:string; end_at:string; room?:string; event_type?:string; course:{code:string;name:string;institution:string} };
const hour = (value:string) => new Intl.DateTimeFormat('fr-BE',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Brussels'}).format(new Date(value));
function Login() { const [email,setEmail]=createSignal(''); const [message,setMessage]=createSignal(''); const signIn=async()=>{ if(!supabase) return setMessage('Configurez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY.'); const {error}=await supabase.auth.signInWithOtp({email:email(),options:{emailRedirectTo:location.origin}}); setMessage(error?.message || 'Lien de connexion envoyé.'); }; return <main class="login"><div class="logo">✣ campus-sync</div><h1>Votre horaire, réuni.</h1><p>Connectez-vous avec votre compte universitaire.</p><input placeholder="vous@universite.be" onInput={e=>setEmail(e.currentTarget.value)}/><button onClick={signIn}>Recevoir un lien de connexion</button><Show when={message()}><small>{message()}</small></Show><p class="note">L’authentification est assurée par Supabase.</p></main> }
function App() { const [session,setSession]=createSignal<unknown>(); const [events,{refetch}]=createResource(()=>session() ? api<Event[]>('/me/events') : Promise.resolve([])); const [courses]=createResource(()=>session() ? api<any[]>('/me/courses') : Promise.resolve([])); const [conflicts]=createResource(()=>session() ? api<any[]>('/me/conflicts') : Promise.resolve([])); const [programs]=createResource(()=>session() ? api<any[]>('/programs') : Promise.resolve([])); const [file,setFile]=createSignal<File>(); const [notice,setNotice]=createSignal(''); onMount(async()=>{setSession((await supabase?.auth.getSession())?.data.session); supabase?.auth.onAuthStateChange((_e,s)=>{ setSession(s); });}); const importFile=async()=>{if(!file())return; try{await uploadIcs(file()!);setNotice('Calendrier importé et synchronisé.');refetch()}catch(e){setNotice(`Import impossible : ${e}`)}}; if(!session())return <Login/>; return <div class="app"><header><div class="logo">✣ campus-sync</div><nav>Calendrier <span>Mes cours</span><span>Programme</span></nav><button onClick={()=>supabase?.auth.signOut()}>Déconnexion</button></header><main><section class="hero"><div><label>MASTER EN CYBERSÉCURITÉ · M1</label><h1>Bonjour</h1><p>Votre calendrier provient de vos sources synchronisées.</p></div><div class="import"><b>Importer un calendrier ICS</b><input type="file" accept=".ics,text/calendar" onChange={e=>setFile(e.currentTarget.files?.[0])}/><button onClick={importFile}>Importer</button></div></section><Show when={notice()}><p class="notice">{notice()}</p></Show><section class="status"><div><b>Connecteurs</b><span>ICS · opérationnel</span><span>ULB TimeEdit · expérimental</span><span>UCLouvain / UNamur / HE2B · non implémenté</span></div><div class="conflict"><b>{conflicts()?.length || 0} conflit(s)</b><span>Calculés à partir de vos événements réels.</span></div></section><section class="calendar"><h2>Calendrier</h2><Show when={!events.loading} fallback={<p>Chargement…</p>}><Show when={events()?.length} fallback={<p class="empty">Aucun événement. Importez un fichier ou une URL ICS pour commencer.</p>}><div class="event-list"><For each={events()}>{event=><article><time>{new Date(event.start_at).toLocaleDateString('fr-BE',{weekday:'short',day:'numeric',month:'short'})}<strong>{hour(event.start_at)} — {hour(event.end_at)}</strong></time><div><span>{event.course.institution}</span><h3>{event.title}</h3><p>{event.course.code} · {event.event_type || 'Cours'} · {event.room || 'Salle non précisée'}</p></div></article>}</For></div></Show></Show></section><section class="courses"><h2>Programme M-SECUC · 2026–2027</h2><p>{programs()?.[0] ? 'Le seed de développement est disponible. Ajoutez-le via l’API ou l’interface programme à venir.' : 'Aucun programme seedé.'}</p><For each={courses()}>{item=><div>{item.course.code} — {item.course.name}</div>}</For></section></main></div> }
export default App; import { render } from 'solid-js/web'; render(()=> <App/>, document.getElementById('root')!);
